# Generated by Django 4.2.3 on 2023-07-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('specilization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_doctor',
            },
        ),
        migrations.CreateModel(
            name='tbl_nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_nurse',
            },
        ),
    ]
